services:
  tvdatahub-db:
    image: postgres:16
    container_name: tvdatahub-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: TVDataHub
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - tvdatahub-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d TVDataHub"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4
    container_name: tvdatahub-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tvdatahub.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - tvdatahub-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - tvdatahub-net

  tvdatahub:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      tvdatahub-db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=tvdatahub-db;Port=5432;Database=TVDataHub;Username=root;Password=root
    networks:
      - tvdatahub-net

networks:
  tvdatahub-net:
    driver: bridge
    
volumes:
  pg_data:
  pgadmin_data:
