// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TVDataHub.DataAccess;

#nullable disable

namespace TVDataHub.DataAccess.Migrations
{
    [DbContext(typeof(TVDataHubContext))]
    [Migration("20250508193556_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TVDataHub.Domain.Entity.CastMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("Birthday");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<int>("TVShowId")
                        .HasColumnType("integer")
                        .HasColumnName("TVShowId");

                    b.HasKey("Id");

                    b.HasIndex("TVShowId");

                    b.ToTable("CastMembers", (string)null);
                });

            modelBuilder.Entity("TVDataHub.Domain.Entity.TVShow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Ended")
                        .HasColumnType("date");

                    b.Property<List<string>>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<DateOnly?>("Premiered")
                        .HasColumnType("date");

                    b.Property<long>("Updated")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TVShows", (string)null);
                });

            modelBuilder.Entity("TVDataHub.Domain.Entity.CastMember", b =>
                {
                    b.HasOne("TVDataHub.Domain.Entity.TVShow", "TVShow")
                        .WithMany("Cast")
                        .HasForeignKey("TVShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("TVDataHub.Domain.Entity.TVShow", b =>
                {
                    b.Navigation("Cast");
                });
#pragma warning restore 612, 618
        }
    }
}
